<a href="https://colab.research.google.com/github/MirzaGe/Assignment-Saylani-Python/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

mylist = [1,2,3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [7]:
nested_list = [[1,2],[3,4],[5,6]]

In [9]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [8]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])